  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: edb022-atv7-consumer
      CodeUri: ../consumer_lambda/
      Handler: lambda_function.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          S3_BUCKET: !Ref BucketName
          S3_OUTPUT_PREFIX: refined/reclamacoes-bancos/
          DB_HOST: !Ref DbHost
          DB_NAME: !Ref DbName
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - SQSPollerPolicy:
            QueueName: !GetAtt ReclamacoesQueue.QueueName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt ReclamacoesQueue.Arn
            BatchSize: 10
            FunctionResponseTypes:
              - ReportBatchItemFailures
